version: "3"
services:
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    volumes:
      - "./couchdb/data:/opt/couchdb/data"
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER_NAME}'
      - 'COUCHDB_PASSWORD=${COUCHDB_USER_PASSWORD}'

  dmv:
    build: ./gov-dmv
    image: gov-dmv
    ports:
      - "8090:3000"
    volumes:
      - "./gov-dmv/public:/opt/app/public"
      - "./gov-dmv/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@couchdb:5984
      - DB_USERS=dmv_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_ID=${DMV_AGENT_ID}
      - AGENT_NAME=${DMV_AGENT_NAME}
      - AGENT_PASSWORD=${DMV_AGENT_PASSWORD}
      - AGENT_LOG_LEVEL=${AGENT_LOG_LEVEL}
      - FRIENDLY_NAME=Gov DMV
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${DMV_URL}
      - CONNECTION_IMAGE_PROVIDER=none
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - couchdb

  ibm-hr:
    build: ./ibm-hr
    image: ibm-hr
    ports:
      - "8091:3000"
    volumes:
      - "./ibm-hr/public:/opt/app/public"
      - "./ibm-hr/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@couchdb:5984
      - DB_USERS=ibm_hr_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_ID=${IBMHR_AGENT_ID}
      - AGENT_NAME=${IBMHR_AGENT_NAME}
      - AGENT_PASSWORD=${IBMHR_AGENT_PASSWORD}
      - AGENT_LOG_LEVEL=${AGENT_LOG_LEVEL}
      - FRIENDLY_NAME=IBM HR
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - MY_URL=${IBMHR_URL}
      - CONNECTION_IMAGE_PROVIDER=none
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - couchdb

  bbcu:
    build: ./bbcu
    image: bbcu
    ports:
      - "8092:3000"
    volumes:
      - "./bbcu/public:/opt/app/public"
      - "./bbcu/views:/opt/app/views"
    environment:
      - DB_CONNECTION_STRING=http://${COUCHDB_USER_NAME}:${COUCHDB_USER_PASSWORD}@couchdb:5984
      - DB_USERS=bbcu_db
      - LOG_LEVEL=debug
      - ACCOUNT_URL
      - AGENT_ID=${BBCU_AGENT_ID}
      - AGENT_NAME=${BBCU_AGENT_NAME}
      - AGENT_PASSWORD=${BBCU_AGENT_PASSWORD}
      - AGENT_LOG_LEVEL=${AGENT_LOG_LEVEL}
      - FRIENDLY_NAME=Big Blue Credit Union
      - AGENT_ADMIN_NAME
      - AGENT_ADMIN_PASSWORD
      - DMV_ISSUER_AGENT_INVITATION=${DMV_AGENT_INVITATION_URL}
      - HR_ISSUER_AGENT_INVITATION=${IBMHR_AGENT_INVITATION_URL}
      - MY_URL=${BBCU_URL}
      - CONNECTION_IMAGE_PROVIDER=none
      - CARD_IMAGE_RENDERING=none
      - ADMIN_API_USERNAME
      - ADMIN_API_PASSWORD
    links:
      - couchdb
